[package]
name = "kettle-boot-api"
version = "0.1.0"
authors = ["TehcJS <tehcdev@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uefi = "0.8.0"
